import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { jobsAPI } from '../services/api';
import { useAuth } from '../context/AuthContext';
import toast from 'react-hot-toast';
import './PostJob.css';

const JOB_TYPES = ['full-time', 'part-time', 'contract', 'internship', 'remote'];
const EXP_LEVELS = ['entry', 'mid', 'senior', 'lead', 'executive'];

const PostJob = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [generating, setGenerating] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [aiSkillsInput, setAiSkillsInput] = useState('');
  const [form, setForm] = useState({
    title: '', company: user?.company || '', location: '', jobType: 'full-time',
    experienceLevel: 'mid', salaryMin: '', salaryMax: '', description: '',
    responsibilities: [''], requirements: [''], requiredSkills: [''],
    niceToHaveSkills: [''], benefits: [''], openings: 1,
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setForm((p) => ({ ...p, [name]: value }));
  };

  const handleArrayChange = (field, index, value) => {
    setForm((p) => {
      const arr = [...p[field]];
      arr[index] = value;
      return { ...p, [field]: arr };
    });
  };

  const addItem = (field) => setForm((p) => ({ ...p, [field]: [...p[field], ''] }));
  const removeItem = (field, idx) => setForm((p) => ({ ...p, [field]: p[field].filter((_, i) => i !== idx) }));

  const handleGenerateJD = async () => {
    if (!form.title) { toast.error('Enter a job title first'); return; }
    setGenerating(true);
    try {
      const skills = aiSkillsInput.split(',').map((s) => s.trim()).filter(Boolean);
      const { data } = await jobsAPI.generateJD({
        jobTitle: form.title, skills, experience: form.experienceLevel,
        jobType: form.jobType, company: form.company,
      });
      const jd = data.generatedJD;
      setForm((p) => ({
        ...p,
        description: jd.overview || p.description,
        responsibilities: jd.responsibilities?.length ? jd.responsibilities : p.responsibilities,
        requirements: jd.requirements?.length ? jd.requirements : p.requirements,
        niceToHaveSkills: jd.niceToHave?.length ? jd.niceToHave : p.niceToHaveSkills,
        benefits: jd.benefits?.length ? jd.benefits : p.benefits,
        requiredSkills: jd.skills?.length ? jd.skills : p.requiredSkills,
      }));
      toast.success('🤖 Job Description generated by Gemini AI!');
    } catch (err) {
      toast.error(err.response?.data?.message || 'AI generation failed');
    } finally {
      setGenerating(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!form.title || !form.description || !form.location) {
      toast.error('Please fill required fields'); return;
    }
    setSubmitting(true);
    const cleanArr = (arr) => arr.filter((s) => s.trim());
    try {
      await jobsAPI.create({
        ...form,
        responsibilities: cleanArr(form.responsibilities),
        requirements: cleanArr(form.requirements),
        requiredSkills: cleanArr(form.requiredSkills),
        niceToHaveSkills: cleanArr(form.niceToHaveSkills),
        benefits: cleanArr(form.benefits),
        salaryMin: form.salaryMin ? parseInt(form.salaryMin) : undefined,
        salaryMax: form.salaryMax ? parseInt(form.salaryMax) : undefined,
      });
      toast.success('🎉 Job posted successfully!');
      navigate('/recruiter/dashboard');
    } catch (err) {
      toast.error(err.response?.data?.message || 'Failed to post job');
    } finally {
      setSubmitting(false);
    }
  };

  const DynamicList = ({ field, placeholder, label }) => (
    <div className="form-group">
      <div className="flex-between" style={{ marginBottom: '0.5rem' }}>
        <label className="form-label">{label}</label>
        <button type="button" className="btn btn-secondary btn-sm" onClick={() => addItem(field)}>+ Add</button>
      </div>
      {form[field].map((item, i) => (
        <div key={i} className="list-input-row">
          <input
            className="form-input" value={item} onChange={(e) => handleArrayChange(field, i, e.target.value)}
            placeholder={`${placeholder} ${i + 1}`}
          />
          {form[field].length > 1 && (
            <button type="button" className="btn btn-danger btn-icon btn-sm" onClick={() => removeItem(field, i)}>✕</button>
          )}
        </div>
      ))}
    </div>
  );

  return (
    <div className="post-job-page">
      <div className="container">
        <div className="post-job-header">
          <h1>📝 Post a New Job</h1>
          <p>Fill in the details or use Gemini AI to generate the job description</p>
        </div>

        {/* AI Generator */}
        <div className="ai-generator-card card">
          <div className="ai-gen-header">
            <div className="ai-icon">🤖</div>
            <div>
              <h3>Gemini AI Job Description Generator</h3>
              <p style={{ fontSize: '0.875rem', color: 'var(--text-muted)' }}>Enter a job title & skills, and let AI write the full JD for you</p>
            </div>
          </div>
          <div className="ai-gen-form">
            <input
              className="form-input" placeholder="Required Skills (comma separated): React, Node.js, MongoDB..."
              value={aiSkillsInput} onChange={(e) => setAiSkillsInput(e.target.value)}
            />
            <button className="btn btn-primary" onClick={handleGenerateJD} disabled={generating}>
              {generating ? <><span className="spinner" /> Generating with AI...</> : '✨ Generate JD with Gemini'}
            </button>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="post-job-form">
          <div className="form-section card">
            <h3>📌 Basic Information</h3>
            <div className="form-grid-2 mt-2">
              <div className="form-group">
                <label className="form-label">Job Title *</label>
                <input name="title" value={form.title} onChange={handleChange} className="form-input" placeholder="Senior Full Stack Developer" required />
              </div>
              <div className="form-group">
                <label className="form-label">Company *</label>
                <input name="company" value={form.company} onChange={handleChange} className="form-input" placeholder="Tech Corp Ltd." required />
              </div>
              <div className="form-group">
                <label className="form-label">Location *</label>
                <input name="location" value={form.location} onChange={handleChange} className="form-input" placeholder="Bangalore, India / Remote" required />
              </div>
              <div className="form-group">
                <label className="form-label">Openings</label>
                <input type="number" name="openings" value={form.openings} onChange={handleChange} className="form-input" min={1} />
              </div>
              <div className="form-group">
                <label className="form-label">Job Type</label>
                <select name="jobType" value={form.jobType} onChange={handleChange} className="form-select">
                  {JOB_TYPES.map((t) => <option key={t} value={t}>{t}</option>)}
                </select>
              </div>
              <div className="form-group">
                <label className="form-label">Experience Level</label>
                <select name="experienceLevel" value={form.experienceLevel} onChange={handleChange} className="form-select">
                  {EXP_LEVELS.map((l) => <option key={l} value={l}>{l}</option>)}
                </select>
              </div>
              <div className="form-group">
                <label className="form-label">Salary Min (₹)</label>
                <input type="number" name="salaryMin" value={form.salaryMin} onChange={handleChange} className="form-input" placeholder="500000" />
              </div>
              <div className="form-group">
                <label className="form-label">Salary Max (₹)</label>
                <input type="number" name="salaryMax" value={form.salaryMax} onChange={handleChange} className="form-input" placeholder="1200000" />
              </div>
            </div>
          </div>

          <div className="form-section card">
            <h3>📋 Job Description *</h3>
            <div className="form-group mt-2">
              <textarea name="description" value={form.description} onChange={handleChange} className="form-textarea" rows={8} placeholder="Describe the role, company, and opportunity..." required style={{ minHeight: 200 }} />
            </div>
          </div>

          <div className="form-section card">
            <h3>🎯 Responsibilities</h3>
            <div className="mt-2">
              <DynamicList field="responsibilities" placeholder="Responsibility" label="" />
            </div>
          </div>

          <div className="form-section card">
            <h3>✅ Requirements</h3>
            <div className="mt-2">
              <DynamicList field="requirements" placeholder="Requirement" label="" />
            </div>
          </div>

          <div className="form-section card">
            <h3>💡 Required Skills</h3>
            <div className="mt-2">
              <DynamicList field="requiredSkills" placeholder="Skill (e.g. React, Node.js)" label="" />
            </div>
          </div>

          <div className="form-section card">
            <h3>🎁 Benefits & Perks</h3>
            <div className="mt-2">
              <DynamicList field="benefits" placeholder="Benefit" label="" />
            </div>
          </div>

          {/* Sticky bottom bar — always visible */}
          <div style={{
            position: 'sticky', bottom: 0, zIndex: 50,
            background: 'rgba(10,10,15,0.95)', backdropFilter: 'blur(16px)',
            borderTop: '1px solid rgba(99,102,241,0.2)',
            padding: '1rem 1.5rem', display: 'flex', gap: '1rem',
            justifyContent: 'flex-end', alignItems: 'center', marginLeft: '-1.5rem', marginRight: '-1.5rem',
          }}>
            <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginRight: 'auto' }}>
              {form.title ? `📝 "${form.title}"` : 'Fill all required fields to post'}
            </span>
            <button type="button" className="btn btn-secondary" onClick={() => navigate(-1)}>Cancel</button>
            <button type="submit" className="btn btn-primary" disabled={submitting} id="post-job-submit">
              {submitting ? <><span className="spinner" /> Posting...</> : '🚀 Post Job'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default PostJob;
